api_platform:
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]
        xml: [ 'application/xml' ]
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    title: 'PHP / Symfony Ingenosya - API'
    version: '1.0.0'
    show_webby: false
    allow_plain_identifiers: true
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 10
        pagination_enabled: true
        pagination_client_enabled: true
    collection:
        pagination:
            enabled_parameter_name: pagination # optional
